-- 1. CENTRES
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('rec08W29gCsOAi1uc', 'club-ritmica-girona', 'Club Rítmica Girona', 'C. Aurora Bertrana, 35', '', 'clubritmicagirona@hotmail.com', 'http://ritmicagironaclub.blogspot.com', 'Girona - Vila-roja i Font de la Pólvora', 'Club de gimnàstica rítmica de Girona. Entrena al Pavelló de Vila-roja i al Pavelló de Fontajau. Ofereix gimnàstica rítmica com a activitat extraescolar a diverses escoles i com a activitat de club.', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('rec0aoeSN0AuOngrB', 'psigma-girona', 'Psigma Girona', 'C. Mestre Francesc Civil 4', '972 299 016', 'info@psigma.cat', 'girona.psigma.cat', 'Girona - Eixample', 'Centre de psicologia amb aula extraescolar d''educació emocional. Espai de desenvolupament de competències emocionals.', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('rec0ddlZph90jdUUf', 'cpa-girona', 'CPA Girona', 'C. Josep Aguilera i Martí, 2', '', 'cpagirona@gmail.com', 'https://cpagirona.cat', 'Girona - Montilivi-Palau', 'Club esportiu dedicat a la pràctica del patinatge artístic. Ofereix patinatge com a activitat extraescolar a diverses escoles de Girona.', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('rec1RQmz9G4eDCzOq', 'girona-judo-girona', 'Girona Judo', 'Av. Josep Tarradellas, 22-24, 17007 Girona', '972 222 053', 'judo@gironajudo.com', 'https://gironajudo.com', 'Girona - Domeny i Fontajau', 'Club de judo fundat el 1977. Ofereix judo com a activitat extraescolar a diverses escoles de Girona. Seu principal al Pavelló Municipal Fontajau.', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('rec2Awnf1d1cjvRse', 'anglo-school-celra-girona', 'AngloSchool Celrà', 'Aumet 50 bx. local 7​', '972 909 111', 'info@angloschool.cat', 'angloschool.cat', 'Celrà', 'Think English, Speak English.
A AngloSchool creiem que aprendre anglès és molt més que estudiar vocabulari o completar
exercicis.
És escoltar, provar, equivocar-se, tornar-ho a intentar, guanyar confiança i arribar a utilitzar
l’idioma de manera real.
Fa més de 30 anys que acompanyem infants, adolescents i adults en aquest procés, amb una
metodologia pràctica, comunicativa, vivencial i adaptada a cada etapa.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/fJv0pRm3uLAfHY4YO42RBA/nU3-CVdKUV8NTnR-JdEXXCsQ_EuHLlTX_6FBaHgntr-UGF5mFUZ5iOc7YhvZlnWrSCWR_RSoy9x4i1P6MxhIHS5vguFHe3w50_1vY6IjsxJDzMGE-MVQB_5l5D2b-6P0K-sPywL4Z7rsa1xQfvSOjtahDuhPrPDrKPyk0hfvyoY/tby6taa2XMfT8Pw4ZI-KRPgEQ-kNCC-eUdWAPVJ_Wmc', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('rec501UGQSSPz8VwU', 'anglo-school-salt-girona', 'AngloSchool Salt', 'Manuel de Falla, 30', '972 242 780', 'info@angloschool.cat', 'angloschool.cat', 'Salt', 'Think English, Speak English.
A AngloSchool creiem que aprendre anglès és molt més que estudiar vocabulari o completar
exercicis.
És escoltar, provar, equivocar-se, tornar-ho a intentar, guanyar confiança i arribar a utilitzar
l’idioma de manera real.
Fa més de 30 anys que acompanyem infants, adolescents i adults en aquest procés, amb una
metodologia pràctica, comunicativa, vivencial i adaptada a cada etapa.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/fJv0pRm3uLAfHY4YO42RBA/nU3-CVdKUV8NTnR-JdEXXCsQ_EuHLlTX_6FBaHgntr-UGF5mFUZ5iOc7YhvZlnWrSCWR_RSoy9x4i1P6MxhIHS5vguFHe3w50_1vY6IjsxJDzMGE-MVQB_5l5D2b-6P0K-sPywL4Z7rsa1xQfvSOjtahDuhPrPDrKPyk0hfvyoY/tby6taa2XMfT8Pw4ZI-KRPgEQ-kNCC-eUdWAPVJ_Wmc', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('rec8bSYPwdb4jZCLe', 'escola-musica-sant-gregori-girona', 'Escola de Música Sant Gregori', 'Sant Gregori', '605061155', 'info@escolademusica.org', 'escolademusica.org', 'Sant Gregori', 'Especialitzada en educació musical infantil. Classes adaptades a diferents edats.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/lvDN8Y2kKwT1BAl6xv3JvQ/WXG3Xp0vIxVqKjKJtF6TEHZ3XvWUiWyP-VptBV1z_DOahFQH6vunYkpLsExHA8TDkafvYEfRzbOkO6eTyewtBIeMsbn2plhuGIL0OCGZyQ_GpCIsQwqdr6QTLm7IvTgaEjt-vWTYJ0pfd3HF849pLEuQiPtjPj-8tEE7M94JHmqQPZ5PGewKF_1ic3cOugaX/qqmgLxTeMRKwMfUg86Yzu-dg-5WeErlrneTrxbG25LE', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('rec8fCklQ7FxUFQwm', 'local-social-sant-daniel-girona', 'Local social de Sant Daniel', 'Carrer de les Monges, 18-20', '', 'ccbarrivell@ajgirona.cat', '', 'Girona - Sant Daniel', '', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/eOn1aLj9xOWwZcc5CwIJ8A/7IyH6EqqIIhxo1khDk2hkz-Gps5uhGuDiq-pY2Y__3fscoH0U6D0S5zzMqxwKxs7rFkY2RYe1av7Y2cMaNjYFo5-fI7oTsr6flc5sFyqRM8FrHOpQkhUN9xWShtjAzD-ID5XqBjmoEgUvr2vSKkGR6CXGlVAnQd3AmY0bOkwYAM/m0sgNWHpliGjsU-REkuv4vL4me32Wk5wf2KRw5cpBg8', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recA3O8RKLiSnLOpG', 'centre-civic-onyar-girona', 'Centre Cívic Onyar', 'C. Camp de la Plana, 13 ', '972 010 298', 'cconyar@ajgirona.cat', 'www.girona.cat/ccivics', 'Girona - Vila-roja i Font de la Pólvora', 'El Centre Cívic Onyar (1991) és un equipament municipal amb un fort arrelament al sector Est (Vila-roja, Font de la Pólvora, Mas Ramada i Grup Sant Daniel). Està situat en un punt equidistant de tots els barris de la zona, que facilita una participació propera i accessible.

Els seus orígens parteixen de la demanda de l''associacionisme local per obtenir espais de trobada i activitat, i han configurat el seu caràcter dinàmic, amb un important nivell de participació de la població del mateix territori.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/eOn1aLj9xOWwZcc5CwIJ8A/7IyH6EqqIIhxo1khDk2hkz-Gps5uhGuDiq-pY2Y__3fscoH0U6D0S5zzMqxwKxs7rFkY2RYe1av7Y2cMaNjYFo5-fI7oTsr6flc5sFyqRM8FrHOpQkhUN9xWShtjAzD-ID5XqBjmoEgUvr2vSKkGR6CXGlVAnQd3AmY0bOkwYAM/m0sgNWHpliGjsU-REkuv4vL4me32Wk5wf2KRw5cpBg8', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recB1BWlEtgd7OH1i', 'associacio-juvenil-salsa-jove-girona', 'Associació Juvenil Salsa Jove', ' Carrer de Josep Maria Prat i Roca, 12, 14', '699 008 522', 'esquerradeltersalsajove@gmail.com', 'https://www.salsajove.org/', 'Girona - Domeny i Fontajau', 'Som molt més que una associació sense ànim de lucre. Som un equip apassionat pel lleure, l’educació i la transformació social. Treballem perquè infants, joves i famílies visquin experiències úniques i creixin en valors. Descobreix-nos!', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/k0sEKZGDHl84caBYRFb1DQ/R1tpHNFDR5JAeZZ5pBR94QpP4r1IB-91n8487x2irPLCsL5MnbTsMsDgZl02dqMoqV5hTF3sNli4xzb_W8-6V7hbUiZ1IX2-8dXVGTqVQRl4Sh1wBecE0Eg_t1A1Gwkkw0tqcGz0THDur027uZ0K241DeZBSQ43o43dpOrQW-J24QpdO81Fr19m9qcq6TJCM9sgnm0qrg0Z5j8MXl0UXZg/oyUfEvgQgSo2FkxJs2KX_V4xo9mVJdATG-dOnQR7O5w', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recBIgxqTPTNfkQda', 'emg-escola-musica-girones-girona', 'Escola de Música del Gironès', 'Carrer de Josep Ametller i Viñas, 8', '972 235 600', 'info@emg.cat', 'emg.cat', 'Girona - Eixample', 'Escola de música amb ofertes per a totes les edats. Programa de músics moderns', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recD4QWR0oxokvoLf', 'museu-art-girona', 'Museu d''Art de Girona', 'Carrer Força 27', '972 41 40 58', ' museuart_girona.cultura@gencat.cat', 'museuart.cat', 'Girona - Barri Vell', 'El Museu d’Art de Girona desenvolupa una àmplia oferta d’activitats educatives adaptades als diferents cursos escolars, des de tallers destinats als més petits, els alumnes d’educació infantil, fins a activitats pensades per a l’alumnat de batxillerat.', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recDAfgL2O8ddJbmE', 'cb-sant-narcis-girona', 'CB Sant Narcís', 'Pavelló d''esports de Palau. c/ Josep Aguilera i Martí, 2. Girona, 17003', '669414273', 'info@cbsantnarcis.cat', 'https://www.cbsantnarcis.cat', 'Girona - Montilivi-Palau', 'Club de bàsquet de formació per a nens i nenes a partir de 5 anys. Abasta barris de Palau Sacosta, Montilivi, Pla de Palau, Sant Narcís i els Químics. Aprox. 150 jugadors/es. Ofereix bàsquet com a extraescolar a diverses escoles.', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recDHighsW2BE5ebR', 'club-escacs-girona', 'Club d''Escacs Gerunda', 'Centre', '972415600', 'info@clubescacs.cat', 'clubescacs.cat', 'Girona - Centre', 'Club dedicat a l''ensenyament i promoció dels escacs. Cursos per a principiants i jugadors avançats de totes les edats.', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recDN4FdyEBI8hBR4', 'conservatori-isaac-girona', 'Conservatori de Música Isaac Albéniz', 'Centre', '972184000', 'info@cmg.cat', 'cmg.cat', 'Girona - Centre', 'Conservatori oficial de música. Ofereix estudis de grau elemental', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recDnhIx5RjzsO4IQ', 'anhel-girona', 'Centre d''Estudis Anhel', 'Carrer de la Creu, 43, entresol 2a, 17002', '609 531 021', 'anhelgirona@centreestudisanhel.cat', 'centreestudisanhel.cat', 'Girona - Eixample', 'El Centre d’Estudis Anhel de Girona ofereix un suport acadèmic de qualitat a l’alumnat de la ciutat i voltants. Som especialistes en reforç escolar, classes de repàs i anglès per a diferents nivells educatius.', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recE4VGi6iGEmFOSD', 'english-girona', 'English Girona', 'Hortes 22, Entresól B2. 17001', '671 940 129', 'secretaria@englishgirona.net', 'www.englishgirona.net', 'Girona - Barri Vell', 'English Girona és una acadèmia especialitzada en l''ensenyament d''idiomes per a infants, adolescents i adults. Oferim classes d''anglès en grup i particulars, preparació d''exàmens oficials de Cambridge (Young Learners, A2 Key, B1 Preliminary, B2 First, C1 Advanced i C2 Proficiency), cursos intensius, reforç escolar i anglès per a empreses.

Treballem amb una metodologia comunicativa i dinàmica, adaptada a cada etapa educativa, amb l''objectiu que els alumnes desenvolupin les seves competències lingüístiques de manera pràctica i efectiva. Som centre preparador oficial d''exàmens Cambridge i comptem amb una àmplia experiència en la preparació de certificacions oficials.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/hY85ioJHGeQjCLTnUq7xBQ/9eLU7yjffUGuYmxKkPLgExwaKHfe9M76NG_Yg949KLEa-tju2DCe7qYY_LWP82hgTccxB3iBl1lwgGNPG49Amj_cxypjIxPqq9Fc8YLBdWb80I6cRQbg5olrUjYh1MkRRZgp4juBsVa-j1R1rOhN3y_D22sHHoQ27_TYBaV-Fzw/sgHVIHeJvkQOPc736YbUmR8NOkGafgMGt19gDFPi7rE', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recEK5NjkjVX97lNl', 'institut-xines-siwei-girona', 'Institut Xinès Siwei', 'Av. Sant Narcís, 14', '695 85 15 06', 'info@institutxines.com', 'https://www.institutxines.com/ca/', 'Girona - Sant Narcís', 'Institut de Llengua i Cultura Xinesa de Girona és un centre educatiu i cultural qualificat com l''escola de xinès a Girona, tenim més de vint anys d’experiències en l´ensenyament del xinès mandarí tant pels catalanes com pels xinesos d’origen xinès . Oferim cursos per a nens de primària, cursos per a estudiants d´ ESO i Batxillerat, i també cursos per a adults. Des de fa sis anys, col·laborem amb les escoles, instituts i acadèmies d´idiomes per a establir els cursos extraescolars i curriculars del xinès mandarí. També organitzem conferencies, seminaris i altres activitats culturals amb
les biblioteques, les escoles i altres institucions culturals a Girona.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/c5eBAJF5saoHTAINQWnObg/P842gAYJtQMOEEJTj4oJafPNzUpA-5SG8VqZSK3MEYsOscoKddBcwM1w_nlXk73ekRM9xysRKfDFyPyh4sFhzOGrzia6En4wtxqrhORuWHM5yAoRR48JMeu0maiCm6_2F-O0lbD_VJs7I0s_OoPIQJelHY_PgyQ6As0vTjWI21c/QUJg1vOTMlmzsCPIQ3gIdlTld5O7OlZxIb3V9XMvYJg', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recEKDGJ8ycpohvWR', 'agro-rural-surf-girona', 'Agro Rural Surf', 'C/ de les Salines, 16, L''Estartit', '660 895 260', 'agroruralsurf@gmail.com', 'https://www.agroruralsurf.com', '', 'A les nostres extraescolars de skate, els infants aprenen els fonaments d’aquest esport, incloent-hi tècniques bàsiques d’equilibri i moviments que els permetran ser més precisos en els trucs. A més, també els ensenyem molts valors de l’skate com el respecte, l’esforç o la perseverança.

Els nostres programes d’extraescolars s’adrecen a alumnes de diferents edats i nivells d’habilitat. Entenem que cada infant és únic, per això treballem per crear una experiència personalitzada que s’adapti als seus objectius individuals.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/KHBBxWfJ84SVWrh8VzN1JQ/bXvxXmxpe2o9n0r8lVV0iRDBEkz7JP6W-R6WfJHjYC6rUnRMQ1NHyyVfHYTJN-ANj4-FkqjxBLPfQWMZBSde6Li6b5VUUZyV6Oeppl410lJSSrlxRGHZkybf84b489IBHNUkhCGSVK7gxRFp89p1yk7t6Jx93dqx7NE8zLtTWD0/8sCWA-9kGnBlYCsQnpYiszQWADAsJiOtoQFPmhANiBA', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recFEBmWiPvpcOMR5', 'imagina-art-girona', 'Imagina Art', 'Carrer de la Rutlla, 130,', '614 34 41 10', 'imaginagironaart@gmail.com', 'www.imaginaart.com', 'Girona - Eixample', 'Som un centre d’experiències artístiques a Girona, enfocat principalment en la ceràmica i la pintura, a més d’oferir puntualment altres tallers.

Treballem amb artistes locals, oferim diverses experiències per totes les edats i nivells. Recorda que és imprescindible reservar abans de venir, ja que les places són limitades.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/e03Urhu-H-iKiT7Y_ySsvQ/trJbVVT1WZAu2flsU8s9xSGc3v6TW1N3KqTDnrp1qfubaK6-JIs-1TXrEK64z6sqC2_f4yKPIlypjwiA5hEZ0qYvXYFr7B0IMc9P9UU4tvUnFZieoENdvCiFyCnS4zcSbsVLAE87CC-U3yX7qwmF4N6cHGKBfucD09VgAh9VsNw/mvcH0hDLsloOyHsL388ou2JE2leNJQYpv8Kv55dxJKY', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recG3q6FhSIL8d58N', 'preludi-girona', 'Preludi', 'C/ Marquès Caldes de Montbui 111-113', '690 939 988', 'escolademusicapreludi@gmail.com', 'http://www.preludi.cat/', 'Girona - Eixample', 'Escola de música de Girona. Ofereix guitarra, música i sensibilització musical com a extraescolar a l''Escola Pericot i altres centres.', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recGAl2tXVi7wZkwb', 'associacio-reach-girona', 'Associació Reach', 'Carrer Joan Reglà 10 baixos', '613 23 49 11', 'associacioreach@gmail.com', 'https://associacioreach.org/ca/', 'Girona - Eixample', 'L’Associació Reach té com a missió la sensibilització comunitària per a la prevenció de l’abús sexual infantil.

La sensibilització i la conscienciació dels i les professionals de l’educació que intervenen amb persones menors d’edat.

La sensibilització dels pares i mares que trenqui els mites de què és i com pot passar l’ASI.

La sensibilització dels i les agents socials i professionals vinculats a l’àmbit de la salut i del lleure, per tal d’aconseguir la identificació precoç i efectiva i la derivació als serveis corresponents.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/pn8zQDQJj4U7OVBms30d0A/FgojeeUm_RCnTD9wduUVqnigiOCj8jY_TVry96Hh8VfARbdgvkCCKLYqVA2X4cjbvKgxRydvIgvq5k8rxiFIRV6JjK--nK5MA-wBBdt_ZPVSVGGOJq1f-MswKmcqsXOs1qykT0vkcVlucLoEMRBCdQ/P5D0KrNbIABM5TCUaD_UupxdcZSdzeudIE-Wuyjm1po', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recGHeFpoHS9TzZPf', 'nipponia-idiomes-girona', 'Nipponia Idiomes', 'Carrer de la Rutlla, 106', '615 14 82 75', 'info@nipponia.cat', 'https://www.nipponia.cat/', 'Girona - Eixample', 'Nipponia va obrir les portes l’any 2005 com el primer centre privat especialitzat en llengües orientals de Catalunya, amb cursos de japonès, xinès i coreà, a més d’anglès, francès i alemany.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/8sVZ_ikTfhxq2xXbyILpSw/hTewnFhTnEdhK1g-w0ALlW9-NOQXgYuKXAMV3iykdxBbO0WgJ-5UTe61mktr23llIs-jS5k4IGOIlA40RbopeFT5znnDUAWfcXsThyeGetGm8nF44jYomU_aUG8mMEzV0gKQ1VMiiDeiwgqHPeNoMJj8l8XVwFJSXdB0JleJg5E/koVz5j2TQr17GSr3p5n3tpiwIer3Y28fnvvq8EGl1ko', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recHgLj4ryjLawaNz', 'eica-girona', 'Eica', 'C/ Emili Grahit, 73', '97 221 93 39', 'Tlf. 601 37 40 45', 'https://eica.cat/', 'Girona - Eixample', 'Apliquem el nostre mètode d’aprenentatge estructurat i sistematitzat, enfocat en el funcionament del cervell i la pràctica de les 4 habilitats lingüístiques per aconseguir la veritable fluïdesa en el nou idioma.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/3maGFCqtPJ3Jvxt_ec5O3Q/z42iVl7nZ7YBjJqogNHhHGUs7gIBuElfDmqy9vBerrkPz5HnnhY5cwkBrQexQ_tIRsgvlQTYYMyWxG4hDdZxoGhFdWzW8DdOdYFBkThPncLTxnPRHCf-p8HkgA5uLdwepkckAvGTDxqIkyeA759-PgwEOyulBmH7JCnbrqxLvZ8/Mr8xBf91v9TqqR6_32Jr63F0ZJ_xmGmCXsbmBrYsS-g', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recIAWgVhPyjRufJ9', 'girolingua-girona', 'Girolingua', 'C/ Enric-Claudi Girbal i Nadal, 23', '972 22 25 69', 'girolingua@girolingua.cat', 'https://girolingua.cat/', 'Girona - Eixample', 'Girolingua és una acadèmia d’idiomes ubicada al centre de Girona. Fundada l’any 1999 per Núria Farró Negra i Mònica Gou Joher, llicenciades en Filologia Anglo-Germànica per la Universitat Autònoma de Barcelona (UAB), Girolingua és una escola amb una àmplia experiència en l’ensenyament de l’anglès i l’alemany.

L’acadèmia va néixer amb la finalitat d’oferir una alternativa a l’ensenyament tradicional dels idiomes tot incidint en la conversa i en les activitats adequades a cada nivell i tipus d’alumne/a, però sense oblidar altres aspectes de l’educació dels alumnes com l’emotivitat, la creativitat, la responsabilitat i la capacitat de treball, importants en el seu camí cap a la formació com a persones.

Amb aquestes idees inicials i en constant innovació i renovació, Girolingua vol ser una acadèmia diferent, on la familiaritat i el tracte personalitzat amb els alumnes i les famílies siguin la principal base per a un bon aprenentatge dels idiomes.

Tot ho fem amb el convenciment que l’aprenentatge dels idiomes és cada vegada més imprescindible en el món globalitzat en el qual vivim. Amb la mateixa il·lusió dels inicis, amb la mateixa motivació, Girolingua segueix treballant per ser molt més que una escola d’idiomes. Vine a visitar-nos! ', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/QzaGo8WAahherJtEweNSQg/rVB4iggPXP9W68R6Lq92m4Sjz8s2dNvEwiYIMLvwRsZViQRj9RCDrOyFsXXSrQ1m_QycBkJJhUUG1reXFFyZyw_C3sGIVvcp1aKN7qGEoeh5MNsCtSpytyQYHPhnFlKmGjTZJ_ivJbog2_BjMgl2ZX7oUgAaBWwV2U-jcE9dd5KiBsG9TSnc0q3lO3pdIVCh/8FrFdF_s_aVGn-mRpw7gnnRJkIcU2uuhj7P2qEt4JTQ', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recIHZJQ0TqaTmicx', 'som-japo-girona', 'Som Japó', 'C/ Andreu Tuyet i Santamaria, 29', '690 963 307', 'info@somjapo.cat', 'https://somjapo.cat/', 'Girona - Montilivi-Palau', 'En japonès tenim una paraula, kotodama, per dir que les paraules tenen ànima.

Descobreix l’ànima de Japó amb nosaltres.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/BSVrwPay5XacRKxeCcfLjg/tTf9fGRYgPp96etgNlDamDmFzd38X7w-PXiwZXtFGK9DJ5nynNLdyefPQTBZVWkzb_PjFywvM1MuUglafUYFSDE-ZlAZ0bewpeK_uELlkDcqzYNfU-M80slR2WyFqRQsxqES_s2SGK-GPoQEgTUYkJmKKiGzgoqpmfeCMKmoXjA/_mcnZhjd1CDddwy9dhu5GkYAz7b1ZLkMjxIOez-Qkxg', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recKEk7mmMaH7QZje', 'happyyoga-girona', 'Happy yoga Girona', 'C/ Sant Agustí, 40, Girona', '616 95 23 14', 'info@happyyogagirona.com', 'https://happyyogagirona.com/', 'Girona - Eixample', 'Centre de ioga a Girona. Ofereix ioga per a nens (6-11 anys) i ioga per a adolescents (a partir de 12 anys), a més de ioga per a adults.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/OhID2k9e7nHyvlVkv8rvrw/tL8wt69ARCoxYVdMZvgtUAqDi9BQ2XaBH8Sa0S3cmm1YkMnCjC4OpaDRk-4VQDrkxeApykL5W5Vx6P2uQQnhInIk_wbOtDsceCFjjboR2_NYtseqeAo6-UIqRsES_yrddxzwOSgx8M1SqtWzSByK7emds4WZyKYjkfgjgmDhJVY/sa4P9s1f9yoCEHEDZPQRcTcGfXrRhUd-IQoyIRbu3tY', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recKFtIi1s8Z82ksC', 'kids-&-us-salt-girona', 'Kids&Us Salt', 'Carrer Francesc Macià, 62', '872 025 167', 'salt@kidsandus.cat', 'https://www.kidsandus.es/ca/academies-dangles/salt', 'Salt', 'A les acadèmies d’anglès Kids&Us, nadons, infants i adolescents aprenen anglès de manera natural i efectiva gràcies al nostre innovador mètode basat en el procés d''adquisició de la llengua materna. El professorat qualificat fa que les nostres acadèmies d’anglès a Salt siguin un espai perfecte en el qual l’aprenentatge sorgeixi de manera natural. A Kids&Us Salt personalitzem l''experiència del nostre alumnat, ja que adaptem cada curs a l''etapa de desenvolupament persona en què es troba; i això permet un aprenentatge integral i progressiu.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/PUWH8uruCUCfooRR16gnjg/MrmHQES0B0EunG8XJuTNO2Fq2lzW812lTyKntFUqzx1SYNZ2zYOk0TuOviQFO3zWjFF7cylMQcO5iskM524Sw3Z6UGBKWM3HTYKoIEiNsutlDiF35lrbg8ELi31cKEeNhiAyh7qGIqKWEGDp3kB0DbKAifn9wPdDYBWuYbNTDNlFF9vCHI56ueCzVxxlCvSI7EeQdljA5BfH7XEtDyIjyw/GEne6MC224-w-b-m02Yev8VeWlN8mZpghdRownpaCbY', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recKdVzY8nxvbba5N', 'la-central-girona', 'La Central', 'Carrer Olivera, 11, 17004 Girona', '609 706 012', 'info@lacentraldimpas.com', 'https://www.lacentraldimpas.com/', 'Girona - Vista Alegre - Carme', 'LA CENTRAL d''Impàs som un centre dedicat a la formació en dansa. Ballet, contemporani, modernjazz, broadwayjazz, hip hop.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/Nka2lGsNpFIprcVtsd1GDw/KTXlN4Mj1G3rOPQPsncWGkk-5OBrpdZyXzY43IdyDoun6785u4Uhnxd1B0eh8L5axCjIz7OmkgsJWfeRrqXj8MJO2Y--N-UOFgW_pHULIfh64Ho568CSB4h46gXncHS8bAK-yUIPj9iqGetw8jcwjNiIK2DXoZWj9n8fg-7D2TU/ysJ7VF1Kgz-cNRWtFcQXqTo-TsOssnf9uYV1vjxaftw', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recKnc1qCAxiLkLiE', 'geieg-sant-ponc-girona', 'GEiEG - Sant Ponç', 'Carrer de l''Esport, 16', '972 20 10 47', 'atenciosocis@geieg.cat', 'https://geieg.cat/', 'Girona - Sant Ponç', 'El Grup Excursionista i Esportiu Gironí (GEiEG) és una entitat sense ànim de lucre consolidada com un referent en l’oferta de serveis esportius, destacant en la formació, l’esport de base i amateur, així com en serveis de benestar per a tota la família.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/RzIW2aAfj_5bETnEw144Mg/6RQFVQay_kJsYy7CYi9MTZpwHm4a5LE_fH7t6KkfR0lfhQRcAxHF-dq5gRAnWmlpPrEO352UQarfeVW9rDNekWT_xqa-0zRMwjC0EUbpN6wZGuHixrgbcvqYT74q4-W46IkK_eFh6U8uhQSRbYbnSmFO6frGqqInw-qigZhZR-g/gSW6LIpoGnTqxKpg4gF_GnGnMuvQNZtztDseEILQy6c', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recN44FzRXvf7XPn0', 'escola-bosc-girona', 'Escola Bosc Girona', 'Carrer de l''Església de Sant Miquel, 18', '650 043 670', 'escolaboscgirona@gmail.com', 'https://www.instagram.com/escolaboscgirona?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==', 'Girona - Montilivi-Palau', '', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/yurtSm5PWOWraje-pSjfsA/bEVuDZugaojc52Iko2gcfaneAyMXxO3pfEbtqqzL4Zq2cQVv7_apeOOeLvbRRQ2WvgfpaoR24_ZHm7tT1Z7QjRGSSOoOYVPZmhlPhQTVAC0w4slEkrl7ntKiBjZVFrHKPY7Kb9QH81IVWYeaX6ym3J2BKn33O3Uq7NC7rJU5UlM/klPNmvTeHu-ySM1x19p9Qo5BHN03A3dEtGHFSB8jPBM', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recN6Rze1OGCVUile', 'mirades-sils-girona', 'MIRADES', 'Masia Can Serra, Veïnat de la Barceloneta, 15', '676313185', 'info@miradessils.com', 'https://miradessils.com/', 'Sils', 'Mirades és un projecte d’educació lliure i viva ubicat a la Masia Can Serra del Veïnat de la Barceloneta de Sils (La Selva, Girona). Oferim un espai d’acompanyament diari per a famílies, amb infants de 9 mesos (aprox.) fins als 6 anys, que busquen una alternativa a l’escola convencional, on el respecte pels ritmes de l’infant i el contacte directe amb la natura són els pilars fonamentals.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/QDpwD1nBMhjzpCPLjUB-1w/trbTsQNL40n_mZV-ZBmY3B7fVwxAw2XSst9syEINRkt_w2I_SW83ubg2la4onSMkKhAzkjVlhW3unm90y6xfeVAt4WQs5vOcBUknyS5Kcf7CttzCG-7bKhCPTHyHPXNMQCITYRdgqP2ZvLCxKVn9t0VV3lUW0qPmusJ36OekodyIM2yqbWm9Hkg-yfmYhEuI3m_6Cdcaq1fBebayd38aKg/HveZO9OfMK2U_No7jXNF7JuiTpX8An7mID3g3MDDFoo', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recNTyAM5IJg0uoKk', 'centre-civic-pedret-girona', 'Centre Cívic Pedret', 'C. Pedret, 152-156', '972 212 568', 'ccpedret@ajgirona.cat', 'www.girona.cat/ccivics', 'Girona - Pedret', 'El Centre Cívic de Pedret el trobem a l’antic hospital de Sant Llàtzer al carrer Pedret, just davant el riu Ter. És un edifici de pedra antic d’estil Gòtic tardà inclòs en l’Inventari del Patrimoni Arquitectònic de Catalunya, i disposa d’una superfície de 230 m², distribuïda en dues plantes amb una sala gran al primer pis, i dues aules a la planta baixa. ', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/eOn1aLj9xOWwZcc5CwIJ8A/7IyH6EqqIIhxo1khDk2hkz-Gps5uhGuDiq-pY2Y__3fscoH0U6D0S5zzMqxwKxs7rFkY2RYe1av7Y2cMaNjYFo5-fI7oTsr6flc5sFyqRM8FrHOpQkhUN9xWShtjAzD-ID5XqBjmoEgUvr2vSKkGR6CXGlVAnQd3AmY0bOkwYAM/m0sgNWHpliGjsU-REkuv4vL4me32Wk5wf2KRw5cpBg8', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recNjXmXns0rO9ve1', 'la-tribu-iogui-girona', 'La Tribu Iogui', '', '666 646 097', 'hola@latribuiogui.cat', 'https://latribuiogui.cat/', 'Caldes de Malavella', 'Oferim classes regulars i tallers de ioga per a infants, famílies i diferents col·lectius. També organitzem experiències a mida per a grups, creant espais per connectar, respirar i créixer junts.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/SbveOaV_QTWMkL8MC6FYDQ/b_AtGJj2WzBV7_EpYsn3ua_sHZRwfv1ft78BNBRQQVhG6PunJY341p5YZh_PViHinNN1q78jntKZetUt8nC8k43iMqUikAD2sY96Sz9YexyLajOom2EWreG5c0bxuEFBe-hqnHYJWzcnhb1hfpkV80FHEAcvQ3CxKHisFSRv_7c/IUPtLe-P5TD7EfA_4UDtgZlfC13kpeEZjDsKefNAHI8', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recOAhITlxeUs1sRA', 'fedac-sant-narcis-girona', 'FEDAC Sant Narcís', 'Carrer Pare Coll, 3', '972 23 31 42', 'coescolars@santnarcis.fedac.cat', 'https://sites.google.com/fedac.cat/coescolarsfedacsantnarcs/activitats', 'Girona - Sant Narcís', 'Escola concertada al barri de Sant Narcís que ofereix activitats coescolars obertes a qualsevol infant de Girona, encara que no estigui matriculat al centre. Les famílies externes paguen 10 € addicionals el primer mes en concepte d''assegurança.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/FsyJ3c-yHjFQWpFGdgLf2g/VeIArfZlCXMNsXQ_msHaeUdw2BlFEbhaKW8bFw_EK-6zINEq1VT72C3n_vwK_1egsrY1d-wFuRvpVMRe0S1kH4jmwrAaPx4mhBQma4ZZnE1md7TGDkGIJ0MHsiiTt-D6jY72MgJ3CavlsHO2LASl-R3hte-xGCjrViXJkc1XNVE/PWTcgYPi9lJMgz7KRbz6k4Eu9fsxHJIqFZ8kwIqqZbE', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recOEFSGYUy1v2uDG', 'centre-dansa-girona', 'Centre Dansa Girona', 'Carrer de Mossèn Baldiri Reixac, 14, 17003, Girona', '619 74 18 67', 'info@centredansagirona.com', 'https://www.centredansagirona.com', 'Girona - Eixample', 'Escola autoritzada pel Departament d''Educació de la Generalitat. Ofereix dansa creativa i dansa com a extraescolar a diverses escoles de Girona.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/I-58vob-fW0aSmhSDFKstQ/MZhl_4Vcb-zvv-jL0tN0qNwYOhEMsJfx5_t7JLzNjpTHV4GZI2NhThUuzm8kHa69jisXBK876fFPaFZZfMQK30Jwex_EpvxFWc92doRxFUAyalV_oQYmYdDtyuNE_1AHp1GreH62K-IE-8O_aGazUA/wTBYdvBRO_tVJLoKGxZ80fLK0a0eQTMGYVJX_KTOaCg', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recOcuTUwnktnolQY', 'abc-idiomes-girona', 'ABC Idiomes', 'C/ Migdia 17', '972 21 23 96', 'info@abcidiomes.com', 'https://www.abcidiomes.com/', 'Girona - Eixample', 'Som una escola d’idiomes amb més de 20 ANYS d’experiència. Oferim classes en grup, particularsi a distància. Aprendre anglès ha de ser divertit! ', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/tGKPYRqv6DuImHl9oENyxg/9Fx3sA1OM9llAviKXSthSrhhwqTl9IjMnT_rnxYmyJGkpWSW2kubMdT1tMRIJW6wrZTg-CWCtxlDIKoGAiDg8w0rICzFIFL9Jc8L4BO3WKI8parSK9Ij6097Mrba8IUi-GcfCa0HR567hq8y1BK1nZkCPgUIct9UjQPTWASFaX8/eGFbgZf7jzpfW-DOs37sUFwqONjw8I6qNA72UXgYVvc', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recPLNJCBuYgE3BwV', 'innovat-educacio-girona', 'Innova''t Educació', 'Carrer Maluquer Salvador, núm. 19. 17002 Girona', ' 972 204 615', ' info@innovateducacio.cat', 'https://innovateducacio.cat/', 'Girona - Eixample', 'Innovat Serveis Educatius SL. És una jove empresa de serveis educatius especialista en robòtica educativa i noves tecnologies aplicades a l''educació i la formació. Gestionem activitats extra-escolars, campaments tecnològics, campus de robòtica, menjadors escolars, centres juvenils, etc. Amb una metodologia innovadora, creativa i centrada en les TIC. També oferim formació per a empreses en el camp de la creativitat, innovació i les noves tecnologies.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/e63vX8UkMvty7zSXnGJFVA/B7pTOlLrFLrCwQGcqYWe9EqjYxMf41n3svxVATMkjQ3vH8rtlgNUjz0_38WtKkOf2V2jB5Xltt6xpxbw3Rp_eQ3C9kBpDMFdcz_8HnuePxFOfn9Tnage7RY-cqO9yfpVdxHbM5Afs1zbw9-6FduFu8giORzjaO6TxNklV3JHWcRGdjj3eNUEeFUvdBI1dJi8o18aoyImNWvjjHmwr5uFFw/yNrNhgpwI2x1UaW5dYLqSBdZeEm31_i_LfXFYz6_g_w', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recPREn2D0nqKJtgr', 'kaliu-espai-creatiu-girona', 'Kaliu espai creatiu', 'Avda Coronel Estrada 118', '654 062 752', 'kaliuespaicreatiu@gmail.com', 'https://www.kaliuespaicreatiu.com/', 'Hostalric', 'Kaliu és un espai que neix de la inquietud de promoure l''art i apropar-lo a tothom. ', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/Sym5NYx0iNrfdr489GnNDg/eqlE-DtaLwC-6xjFrutQ-9U9W7tMkhP_l7ZC2adtGMriiFivOh00c6XhlfBuXwkPWgauPy1vsz1FYXFwSR6BL4ZQk5RMoGuTloixlqIhSkl7ZzFEzYmRDll0Rmuo-XPYFdbfjem4F-ZbKNTbh8u07xik3QHIN-HSShoceHQxVWMOGBb3RrZw4xJjosJZwY8xF28-CwmTESJW-QxEeQshhw/Wx17BjONvmqhvdb2THhJyC5EsdbgqAtVYmhYviaay0w', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recQ695aIqKEWV0Px', 'girona-en-dansa-girona', 'Girona en Dansa', 'Carrer de Josep Ametller i Viñas, 8', '972 22 28 30', 'gironaendansa@gmail.com', 'https://www.gironaendansa.com/', 'Girona - Eixample', 'Escola de dansa autoritzada (centre Ballet Fit®). Ofereix pre-dansa, dansa clàssica, puntes, fisiotècnica, modern jazz i dansa adult. Imparteix Dansa Moderna com a extraescolar a l''Escola Pericot i altres centres.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/LyhgS5cG8Zpj2oOtXVgJQw/kvFhYtzLMkcZ0LWf0UklqGZwrQWOhTOqbi6itoFSpRFegLXpApWAQQbyytVVKLxo1BAh6PmBATJMy-cLx6erd0fkImjEcWC2o8uA3orSFv_KUOVjrXGPglbEIH-mc4BzPoGv3l-2Otidc9bRTYmQkq8Xdfb-U38o_oqKOQdCjTGUkNp9NIrGcQYoYaEz4pV0kTKj1_8ojW8yRYkkHXCUww/j_AphosipJuV12LUO4Nyugd-AfdDQ-ivRIqwvS2BSew', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recQ7yplzVv2G2nH2', 'piscina-santa-eugenia-girona', 'Piscina Municipal Santa Eugènia', 'C. Josep Aguilera i Martí 2', '972237306', 'activitatsesports@ajgirona.cat', 'girona.cat', 'Girona - Santa Eugènia', 'Instal·lacions municipals per a natació infantil', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recRJgMotbNGgoNbw', 'kulturfabrik-girona', 'Kulturfabrik', 'Ronda de Sant Antoni Maria Claret, 15-19, Entresol B', '611 622 822', 'info@kulturfabrikgirona.com', 'https://www.kulturfabrikgirona.com/ca/', 'Girona - Eixample', 'Kulturfabrik és un espai on infants i joves aprenen idiomes de manera lúdica – actualment amb un focus en l’alemany.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/wzNIO8XEAGDPCWqnGbZBJg/OKXLo5P2Lb7lDklYqGuO-bjyKZ-sRKW31wIs5NnaRbN95tE7J2f1jR8cuxS1-1dDXCbvuvU0Hq-OsFd-EKHFVojGMaXGyKqlLsK5qGdh2lSXwGDuxfjS5A-DwxCjVEpVsOo1-EGMZqeRf2HCDi7ukS98A9s37RvYprrJzCQLUrg/qmgGqktlG4BXpscZkENuAgfdRNDcIaFqPQCoHMgfUc8', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recT618bKVEBAVmpP', 'fundacio-torremirona-esport-i-salut-girona', 'Fundació Torremirona - Esport i Salut', 'N-260, Km 47, 17744 Navata, Girona', '972 56 54 29', 'info@fundaciotorremirona.com', 'https://www.clubtorremirona.com', 'Navata', 'La Fundació TorreMirona - Esport i Salut té com a objectiu principal la promoció i la pràctica de l''esport com a mitjà per a la millora de la qualitat de vida de les persones. Treballem per fomentar el desenvolupament personal i social a través de l''esforç, el respecte, el compromís i la solidaritat, contribuint així a crear una societat més sana, activa i solidària.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/6Nc76DcCt9T54WNbfIAtFQ/BDZS1QK9BowWrg-LS4SnwTL3yso12RhLA8YlT8EogiC5P2yeH_BFl8eBg6eJUIqG25b3jK4-1chGXYTe_sFRJr-bj1llFDgPPKDcB7HuWKWBCbourmr6P92Wj039AwIMwW2TruTi_K1TfOsmi9xyYA/6seyHo9QdJkOC-DaMt-SU05HAQLaJnf2gp0EsJaz_Bs', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recULd44Ln90T6rsz', 'centre-civic-santa-eugenia-girona', 'Centre Cívic Santa Eugènia', 'C. Santa Eugènia, 146', '972 245 111', 'ccsantaeugenia@ajgirona.cat', 'www.girona.cat/ccivics', 'Girona - Santa Eugènia', 'El Centre Cívic Santa Eugènia està situat en una antiga masia del segle XV, coneguda com Can Ninetes. És un centre cívic que presenta una àmplia i diversa programació cultural, on les entitats de la zona tenen una important participació. Destaquen les nits literàries, els espectacles, les exposicions i les tertúlies i debats. El conjunt de cursos de plàstica, cuina, ball, ioga, etc., són també un bon referent per a molts de ciutadans i ciutadanes del barri i de la ciutat.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/eOn1aLj9xOWwZcc5CwIJ8A/7IyH6EqqIIhxo1khDk2hkz-Gps5uhGuDiq-pY2Y__3fscoH0U6D0S5zzMqxwKxs7rFkY2RYe1av7Y2cMaNjYFo5-fI7oTsr6flc5sFyqRM8FrHOpQkhUN9xWShtjAzD-ID5XqBjmoEgUvr2vSKkGR6CXGlVAnQd3AmY0bOkwYAM/m0sgNWHpliGjsU-REkuv4vL4me32Wk5wf2KRw5cpBg8', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recVKeSoRWlIRngyO', 'local-social-vista-alegre-carme-girona', 'Local social Vista Alegre - Carme', 'Carrer de Josep Morató i Grau, 8', '', 'vistalegre.gi@gmail.com', 'http://veinsvistalegrecarme.cat ', 'Girona - Vista Alegre - Carme', '', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/eOn1aLj9xOWwZcc5CwIJ8A/7IyH6EqqIIhxo1khDk2hkz-Gps5uhGuDiq-pY2Y__3fscoH0U6D0S5zzMqxwKxs7rFkY2RYe1av7Y2cMaNjYFo5-fI7oTsr6flc5sFyqRM8FrHOpQkhUN9xWShtjAzD-ID5XqBjmoEgUvr2vSKkGR6CXGlVAnQd3AmY0bOkwYAM/m0sgNWHpliGjsU-REkuv4vL4me32Wk5wf2KRw5cpBg8', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recW2bp4m8lOnAUai', 'centre-civic-pont-major-girona', 'Centre Cívic Pont Major', 'C. Pont Major, 67-73', '972 205 244', 'ccpontmajor@ajgirona.cat', 'www.girona.cat/ccivics', 'Girona - Pont Major', 'El Centre Cívic Pont Major (2003) és un equipament municipal adreçat al conjunt de la població, a les associacions del barri i col·lectius diversos. El centre ofereix una programació que s''organitza a través de la participació activa de les entitats i col·lectius del barri. Activitats per a gent gran promogudes per l''Associació de Jubilats La Unió, projectes i cursos dinamitzats pel Col·lectiu de dones La Cata i festivitats populars promogudes per l''associació de veïns i altres associacions de la zona, pretenen ser un clar exemple de dinamització social i cultural del sector.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/eOn1aLj9xOWwZcc5CwIJ8A/7IyH6EqqIIhxo1khDk2hkz-Gps5uhGuDiq-pY2Y__3fscoH0U6D0S5zzMqxwKxs7rFkY2RYe1av7Y2cMaNjYFo5-fI7oTsr6flc5sFyqRM8FrHOpQkhUN9xWShtjAzD-ID5XqBjmoEgUvr2vSKkGR6CXGlVAnQd3AmY0bOkwYAM/m0sgNWHpliGjsU-REkuv4vL4me32Wk5wf2KRw5cpBg8', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recWjPxSrJtZkcJG1', 'playcook-kids-girona', 'The Playcook Kids', 'Carrer dels Mercaders 8', '93 139 43 48', 'info@theplaycook.com', 'https://theplaycookkids.com/ca/casal-verano-cocina-girona', 'Girona - Barri Vell', '', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/TQtxtmzRihqjFluvYGjOPw/6UMm-Y9CNlILIaY16YD1mo5sav4KS0ZTQlhWgcR7Mn4GxjbCVflxL6mAhw5kbmb49bpnPnPbR0v2jiVk_b7vXzvXPz9gRaY_gcnlEsgS5_xTFnzs2c84XfV-G6aKr5yv7LbvFpXOqnqBlqJKeiyl1whyyg6Ku-OJ8Zrxv9P279Bs0x7BukdWnb2U7u7q9WnLeKOJfIbGYhpmNbgqK9IAyw/CJh1i5MQQBzwJ_d_URzU5eKQgdihSQuenx46wV7HPU0', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recXcvKvWb2CrQyb6', 'girona-riders-girona', 'Escola ciclisme Girona - Girona Riders', 'Pavelló Fontajau', '672 53 83 71', 'info@gironariders.com', 'https://www.gironariders.com/', 'Girona - Domeny i Fontajau', 'Des de Girona Riders oferim un extraescolar de ciclisme de muntanya, on es', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/twOsGDdg8M9JhfspKyzAJw/Dex65y51N5GneYsnPwcb9NuhpFs5Q5D8FC4iE54_PQIz89U21gg32Dmqu4orvqksSXw1LwZ6rLg9wCgWhoruWKSqaTm7Jc3RvRRj67Nqw6rIBgxGL1nn1kNe9IdSW9RhqG1bdZ5JJ7qt7hejNKY95-5mSrTWcI3Ay4a9Or_JvSG07fxAjdE9wGHLkDQuAhEgbVqzPNZ6djGSyHh2akac0g/TBH02UvAmK8Z_d-eZnGURwdGDqfijtmejqkL3m2E_QE', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recY1lKxx9NKIypox', 'la-diana-girona', 'La Diana', 'Passeig d''Olot, 68, 17006', '644 251 800', 'hola@ladiana.cat', 'https://ladiana.cat/', 'Girona - Santa Eugènia', 'La Diana és una escola d’arts escèniques inspirada en el mètode Stanislavski, que utilitzen altres centres com Actor’s Studio de Nova York.

Amb el nostre mètode, cada alumne farà un treball d’investigació basat en l’assaig, l’autocrítica i en l’avaluació continuada de cada exercici per trobar les eines necessàries per ser actors i actrius professionals, espontanis, creatius, participatius i constructius.

Volem aconseguir que l’alumne experimenti les emocions reals que viu el personatge jugant a creure i viure les situacions de l''”aquí i ara” de l’escena.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/5frHG0SYKXdaj3GAcBTcrg/3OQhHORZMWJh_B-QGk6xlOOkPjU6DQN7hIO4XjQa37oSRksenf-yNmUCf811h2fZKOCG3Czgqj7cbLCnB-wXKSJrJILgJmVcQAqviSnHJN5ojlfYE9JCNJv50Cf8w2JuI-cYRBAD61nwMPOg49vEAA/cjfRuI_665Fo-ZDoY2uO9Ti8FEMlN0Ul0jIGEhwo-ZU', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recZ0n11wwlz6LRBq', 'taller-barri-girona', 'El Taller Del Barri', 'C/ Canonge Dorca, 20 | 17005 Girona', '972 66 35 04 / 644 449 450', 'info@eltallerdelbarri.com', 'https://www.eltallerdelbarri.com/', 'Girona - Eixample', 'El Taller Del Barri ofereix tota mena de tallers vinculats amb el dibuix  (il·lustració, dibuix amb model en viu, pintura, còmic, manga, dibuix artístic, pirogravat…)', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/E3263lPnAFyaFJc81rH-PA/vj-GRStag2mBtLbGo0O3syybjxkx7VXZCIeBS2_YfMCpKz7IpncF8njHhHfeQYpkAJOFnX8G5lsi4Za6IjEGlrCVuqGdLQR9oebeJqo54FtgonxVIxtqgbVgI-ZYTfo_6pbtvd1PIpN2qrGVo_H7Ps_eHP1uJJCcqS5tOHk3SSY/u0n0xJ81Ghsm414OaOarxVXwYt-Hdm0egz6YSIsShl4', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('reccxzSeIQJMV4VXV', 'qstura-girona', 'Qstura', 'Fàbrica Gassol-Monar', '633 639 012', 'info@qstura.cat', 'qstura.cat', 'Salt', 'L’any 2007 neix Qstura de la necessitat reiterada dels alumnes d’una formació personalitzada i pràctica a Girona on poder fer realitat les seves creacions. Des d’aleshores, Qstura no ha deixat de créixer any rere any, ampliant l’oferta de formacions, activitats i projectes als quals participa. ', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/-V25CTzqFM9uFR9PbXd1qA/XqwPz5fLoj3aNIKTHpz3TbzbHPwOWRU47iPc0fhkeBaAEplyKOG1lvy47691Gi3pC8fX5VZmDUxyE0FPIHLSeQ0h6JqHgx6ymOanVbpEo2EeOTurWdc1qJNkhZpG7L04LQhH8AcCXmTjCVLwHJ93eYhidsy0lRTnwkkp7-9f0nw/tPRgDnUA0fUm5jrGA_MH72udL7ZmfsPlcHTlft3SOZ4', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recdEBB9Q3oWwXw6r', 'codelearn-girona', 'Codelearn Girona', 'Carrer Maluquer Salvador 20, 17002 Girona', '722 664 716', 'girona@codelearn.cat', 'codelearn.cat/girona', 'Girona - Eixample', 'Codelearn és una extraescolar de pensament computacional, programació, robòtica, electrònica i molt més. Hem desenvolupat un mètode que converteix l’aprenentatge de la programació en un joc i anima els alumnes a esdevenir creadors de tecnologia.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/36e0-qOx2QCKfHxBXu_BfA/Sw4Rtl5PLbFJjUIuImbFgmhLFrcTaM8vQ0s9Vfrq4KdXQTU0pqOWrN9nnujDTp58KsFQd7nItOkp-U2aOAnF1AvADwYI2eCmbt44n2Qp9mdecCj34HdjAtJgaKvwDx5U8QDWHi12GD_Zjb0VbhTz288qIlorPAATrD00uQae9pU/oqXihojNs51lw0NzcS1oivt29mW5OTvLmJiv5-dSgNU', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recdoZuN00s0JNyRK', 'tictac-serveis-girona', 'TIC TAC Serveis', 'C/ Pins d''en Ros, 12, 17460 Celrà', '972 494 294', 'info@tictacserveis.com', 'https://www.tictacserveis.com', '', 'Empresa de serveis educatius a Girona. Ofereix extraescolars, casals, monitoratge, idiomes, reforç, mecanografia, ball, costura, ceràmica, ciència i moltes més activitats a diverses escoles de les comarques gironines des de fa més d''una dècada.', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recgUj4gR0bF8MiKP', 'diverfut-academy-girona', 'DiverFut Academy', 'Avinguda de Montilivi, 143 Zona esportiva del campus de Montilivi', '601 374 045', 'diverfut.academy@gmail.com', 'https://diverfutgirona.com/', 'Girona - Montilivi-Palau', 'A Diverfut som un projecte educatiu i esportiu que entén el futbol com una eina per al desenvolupament personal i esportiu de nens i joves. Acompanyem cada jugador i jugadora en el seu creixement, fomentant valors com ara el respecte, l''esforç, el treball en equip i la confiança.

Posem la persona al centre, creant un entorn segur, positiu i motivador on puguin gaudir, aprendre i evolucionar al seu ritme. Treballem amb una metodologia adaptada a cada edat i nivell, que combina aprenentatge lúdic, desenvolupament tècnic i motriu, millora tàctica i acompanyament educatiu i emocional.

El nostre objectiu no és només el rendiment esportiu sinó formar persones amb valors, capaços de superar reptes i gaudir del procés d''aprenentatge.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/fs412bRlr-nSsiFWwLe5SQ/rLqKsUXMwJktyIxi8Ir3xqDwJbX6Z23KAiNX_8BCe8geFuIj2cpUSjnd_iT5UT4eaPNPdU2oK0lhLv2BQWhA8NZ1GX4bV--IoQh0K8b8sP6SEadDVcUT_j-OluSqgSqHhy4JkTyXLeYSLEzsrELEI0qVq9GpVc_7JBjPVAZTV4I/WmH4XnE-kROQryzQhAkkjFTyMyFa0E4AE91LzS5N04g', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recgetecLsdwmaX6k', 'geieg-palau-girona', 'GEiEG - Palau Sacosta', 'Carrer de l''Església de Sant Miquel, 18', '972 22 66 35', 'atenciosocis@geieg.cat', 'https://geieg.cat/', 'Girona - Montilivi-Palau', 'El Grup Excursionista i Esportiu Gironí (GEiEG) és una entitat sense ànim de lucre consolidada com un referent en l’oferta de serveis esportius, destacant en la formació, l’esport de base i amateur, així com en serveis de benestar per a tota la família.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/RzIW2aAfj_5bETnEw144Mg/6RQFVQay_kJsYy7CYi9MTZpwHm4a5LE_fH7t6KkfR0lfhQRcAxHF-dq5gRAnWmlpPrEO352UQarfeVW9rDNekWT_xqa-0zRMwjC0EUbpN6wZGuHixrgbcvqYT74q4-W46IkK_eFh6U8uhQSRbYbnSmFO6frGqqInw-qigZhZR-g/gSW6LIpoGnTqxKpg4gF_GnGnMuvQNZtztDseEILQy6c', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('reciIofi7Tshw66I8', 'up-idiomes-girona', 'UP! IDIOMES', ' Passeig General Mendoza, 7 pral', '972 21 23 54', 'info@upidiomes.cat', 'https://www.upidiomes.cat/', 'Girona - Eixample', 'Situada al bell mig de Girona, ofereix una àmplia gamma de cursos interactius i motivadors tant d''anglès com de francès i altres llengües, amb opcions presencials i també suport online o aules virtuals si és necessari', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/CAI1bIQrWDa3o_XzH639Yw/8uzNiMmY6uVUWpCqCvssO7sMf6_p99j1w9bWRlce9yr2kDB0IwVB1AXSawKESudaqhbiNtVXz_69pu2jH3ltM_14ID5gnNGJR2mCUBa28_1dQgOfygaFoPkUBBu5S0qCrSPd1TqMNahw0uc3pKlWM5gdOo999RN-231Pcs4OHNE/QjmLzpjU8RlJRLp5oUWFVnR6v901JpNMQzORT5Hyuz4', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recifhRNk0AJriirG', 'geieg-sant-narcis-girona', 'GEiEG - Sant Narcís', 'Carrer d''Empúries, 47, 17005', '972 23 44 59', 'atenciosocis@geieg.cat', 'https://geieg.cat/', 'Girona - Sant Narcís', 'El Grup Excursionista i Esportiu Gironí (GEiEG) és una entitat sense ànim de lucre consolidada com un referent en l’oferta de serveis esportius, destacant en la formació, l’esport de base i amateur, així com en serveis de benestar per a tota la família.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/RzIW2aAfj_5bETnEw144Mg/6RQFVQay_kJsYy7CYi9MTZpwHm4a5LE_fH7t6KkfR0lfhQRcAxHF-dq5gRAnWmlpPrEO352UQarfeVW9rDNekWT_xqa-0zRMwjC0EUbpN6wZGuHixrgbcvqYT74q4-W46IkK_eFh6U8uhQSRbYbnSmFO6frGqqInw-qigZhZR-g/gSW6LIpoGnTqxKpg4gF_GnGnMuvQNZtztDseEILQy6c', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recimAsCaXEOyF6AU', 'local-social-pedret-fora-muralla-girona', 'Local social Pedret-Fora Muralla', 'Pujada de la Mercè, 12', '', '', '', 'Girona - Pedret', '', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/eOn1aLj9xOWwZcc5CwIJ8A/7IyH6EqqIIhxo1khDk2hkz-Gps5uhGuDiq-pY2Y__3fscoH0U6D0S5zzMqxwKxs7rFkY2RYe1av7Y2cMaNjYFo5-fI7oTsr6flc5sFyqRM8FrHOpQkhUN9xWShtjAzD-ID5XqBjmoEgUvr2vSKkGR6CXGlVAnQd3AmY0bOkwYAM/m0sgNWHpliGjsU-REkuv4vL4me32Wk5wf2KRw5cpBg8', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('reclfLaYHcc552ANs', 'the-classical-ballet-school-girona', 'The Classical Ballet School', 'Carrer Ibèria 4', '620 43 90 71', 'contact@theclassicalballetschool.net', 'theclassicalballetschool.net', 'Girona - Eixample', 'La nostra escola proporciona una formació en dansa clàssica tant a aquells i aquelles que aspiren a dedicar-se professionalment a la dansa com als que volen viure la seva passió per ballar de manera lúdica, tot i desenvolupant el benestar corporal i emocional que aquest art ens aporta.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/9Jbzl1bMq95r_lmr70DRQw/ApScPi0NZHDIB2GIi_XFdDZ8AJ3htN4N4g1xGJV2UZPQsnsLym7SbL9Mhf95EoO517OI8D2u7mfePc35irRuw0LSbySHtBmwjKh5dweIaN4591BqZzRREV5kIyjWdpMdO3LjxksgWzQ_6XAwWCW4IrcPNHnV1iy8wsbGjwgA8NE/9Cmz7zCZTDstlcrj1eaAOXBFFKMVbSVKlp7D5jWNj4c', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recmJ4g1SaTJycGUy', 'centre-civic-sant-narcis-girona', 'Centre Cívic Sant Narcís', 'Plaça Assumpció, 26-27', '972 237 063', 'ccsantnarcis@ajgirona.cat', 'www.girona.cat/ccivics', 'Girona - Sant Narcís', 'El Centre Cívic Sant Narcís (1989) és un equipament municipal plenament consolidat al barri de Sant Narcís i amb una projecció destacada cap a la resta de la ciutat gràcies a la seva localització, las diversitat d''espais de què disposa i una programació extensa i variada, promoguda cada vegada més a partir de la iniciativa social i cultural. Hi trobem molta participació en els casals (casals, esplais, jocs organitzats...), seguit de les grans activitats organitzades bàsicament per col·lectius i associacions del barri.

', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/eOn1aLj9xOWwZcc5CwIJ8A/7IyH6EqqIIhxo1khDk2hkz-Gps5uhGuDiq-pY2Y__3fscoH0U6D0S5zzMqxwKxs7rFkY2RYe1av7Y2cMaNjYFo5-fI7oTsr6flc5sFyqRM8FrHOpQkhUN9xWShtjAzD-ID5XqBjmoEgUvr2vSKkGR6CXGlVAnQd3AmY0bOkwYAM/m0sgNWHpliGjsU-REkuv4vL4me32Wk5wf2KRw5cpBg8', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recmbEhDkAV6p8pnq', 'sol-de-solfa-girona', 'Sol de Solfa', 'Carme 27-29', '972 100 437', 'info@soldesolfa.com', 'soldesolfa.com', 'Girona - Vista Alegre - Carme', 'L''escola pretén oferir un ensenyament musical de qualitat: pràctic, dinàmic i creatiu. Adaptat a les inquietuds i necessitats particulars dels alumnes de qualsevol nivell i a qualsevol edat.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/2tvxkZ-a3AZ66t9jeeVvCw/Nkr0JVtTogIhrRnS5QUQ6m1QzJlsGUIi6D9K6nJpMVJeyfrhYj96hi8HwrayYBwBjeYeo6G2rnsRxg7X_1LFCEERoykSUGRaEH4X2HCmNDx1TUtss0BwHetPVwNYp_XxdwF9GA85AMHxBlg5l-xtlfWN1Z_fLsTJb7Kqih_4lEw/BietoXxwElWkPHhTDZC74KRSfgoPkeT5MJVwMRJbVRo', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recngrYLYYbP1MdLA', 'recreat-activitats-girona', 'Recrea''t Activitats', '', '628 90 77 33', 'info@recreatactivitats.com', 'https://recreatactivitats.com', '', 'Entitat d''educació en el lleure que ofereix activitats extraescolars creatives i artístiques: manualitats, mà i manetes, art i dibuix, costura, contes i titelles, resolem dubtes, entre d''altres.', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recoLWuJYwfIni4h6', 'algorithmics-girona', 'Algorithmics Girona ', 'C/ Rutlla 112-114, 1r pis, 17003', '622 51 87 32', 'girona@algoacademy.es', 'https://es.alg.academy/centro?url=algorithmics-girona', 'Girona - Eixample', 'Escola de programació per a joves de 6 a 18 anys. Ofereix extraescolars de programació, disseny de videojocs i Scratch a diverses escoles de Girona.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/ZTU3iJz1CZ_DpsjxWUZtTw/Oumegg9epVYhTaopAb7IMXuxef43JEeaLfNRkwP9er85mw1nMn7lCKqzWtKVpMO7ne7CdorMYOfotuKUz1RHsACdUhoJut7Tm1XTXfED6h6cPK66g9lNSxK2d0bXpuQSG3LSEKrXqGo8tFlnOSam-1nXvTzqU0AnUIUCGUwyEFY/7hg7HnI_ZhAO4OL1MMAKx_LT7g8rVs9PTyC9edtiL40', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recocKPYDHMx8CNcG', 'el-galliner-girona', 'El Galliner', 'Els Maristes Avinguda del President Josep Tarradellas i Joan, 5, 7, 17007 Girona', '972 205 884', 'elgalliner@elgalliner.cat', 'https://elgalliner.cat/', 'Girona - Santa Eugènia', 'El Galliner és l''escola de teatre i arts escèniques de referència a Girona per a infants i joves. Ubicat a l''Avinguda del President Tarradellas, al barri de Santa Eugènia, el centre porta anys formant nenes i nenes, adolescents i joves en les disciplines del teatre, el circ i el teatre musical, amb una metodologia pròpia que combina el joc, la creativitat i la tècnica escènica.
L''oferta de El Galliner s''organitza per franges d''edat molt ben definides, des dels 4 anys fins als 18, perquè cada grup treballi al seu ritme i amb els reptes adequats. Els Pollets Artístics (4-6 anys) és el punt de partida: un espai de joc dramàtic i expressió lliure per als més petits. Les Gallinetes (7-8 anys), els Pollastres (9-11 anys), els Nuggets (12-14 anys) i els Galls (15-18 anys) conformen l''itinerari de teatre infantil i juvenil. Per als qui volen combinar veu, moviment i actuació, el Teatre Musical Juvenil (12-18 anys) és una de les propostes més completes del centre. I per als qui s''atreveixen amb l''acrobàcia i les arts del circ, el Circ Juvenil (12-18 anys) ofereix una experiència única a Girona.
El Galliner no és una escola convencional: és una comunitat artística on els joves aprenen a pujar a un escenari, a treballar en equip i a confiar en ells mateixos. Els espectacles de final de curs, oberts al públic, són un dels moments més esperats de la temporada per a les famílies de Girona.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/5mAaCvKas3rlQABF7lK5Gg/B6ZMa4tngNYH6oYf4o3DJ4lgcYRr-tPcSmZFZES4gD0xBTtgP18nnl95_f6BRJ4QUYlY6RJNdQ4sI_GQ7i-PVuR9ZWsdOKoJSIJGLoHVXMIulE5mCwUnRufXhjH_hRuExg3VthIMowt8S8DYhpcV7qquankJ72dWoBmKbX6_89vmF80gXSan5oOgzpG9LHhkudAXIJeU2ApB4ieF6yOD8A/oolTgHat8B4ndCX6RQLsWR9mRS8h687qah8XsAcTn0U', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recozNuemEiv21Gov', 'claudefaula-girona', 'Claudefaula', 'C. Campcardós 37-39 local 3', '972245047', 'info@claudefaula.cat', 'https://www.claudefaula.cat', 'Girona - Santa Eugènia', 'Escola de música i arts de Girona. Ofereix sensibilització musical i música com a extraescolar a diverses escoles del barri de Germans Sàbat i Palau.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/Ykbezm9Fdhiu324CWlXjJQ/8IsKUuRiU2-khmpvtoTzaWDPLILJFDXKyvo9igxt2ZoRoOkEhavxnI7udN5C62jRveXL2nmwRoE3Mf9DtJtTegndbaURpr_viDltQ7puc1x3216aqZ5vvSdBJtn5UL8hOVP1kVcZU-9a7UZJlbmhfI-OzldHrkzasAhtL4m-LgIdDwmpVRBxE2Ei5toKijoO/RKnbb6uxQ8AL2pYhcWQqQf4xT3JM5073q4Al86tkg0E', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recp0vtNGt1HBQ25u', 'espai-fang-girona', 'Espai Fang', 'Carrer de la Creu, 55', '621 285 761', '', 'https://www.espaifang.com/', 'Girona - Eixample', 'Espai Fang és un lloc on la creativitat, l’aprenentatge i la comunitat s’uneixen per donar vida a peces úniques. Ens apassiona compartir el món de la ceràmica amb aquelles persones que desitgen explorar el seu costat artístic i connectar amb materials naturals.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/QqeuNSJtw82mZwdcZlIzuA/TNkSafTKuP2HXC6d6Wh3Q3oAC8tl76f7a8tNAbqMSbewyrRLjfF_JGyaNx8BTbXwLO_420cw-FLA8u3SVQmGcJeRZz4wy5sNVJZxuwi9BNIQs8AvEiQX5Tgd8ZxJfwxGUOwSk-JidP4T-mgbBFOMV2L3YMPJaZ_ljmeodYTmR6w/yBlE7UPFj9NCbxF5I-m-4SID-ob5Cz6UPLdlyv20dSc', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recpG0Qts1G9JA9a6', 'centre-civic-barri-vell-mercadal-girona', 'Centre Cívic Barri Vell-Mercadal', 'C. Cort Reial, 7', '972 010 005', 'ccbarrivell@ajgirona.cat', 'www.girona.cat/ccivics', 'Girona - Barri Vell', 'El Centre Cívic Barri Vell - Mercadal neix amb la intenció de posar l’accent a projectes que es desenvolupin des de l’àmbit social i cultural. Pretén esdevenir un centre d’acollida a totes aquelles associacions i entitats amb iniciatives veïnals i comunitàries. Un enfocament innovador, que contempla la participació ciutadana en tots els seus projectes. Un centre cívic que pretén fomentar la creativitat en el marc de la participació social acollint i impulsat noves iniciatives socials.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/OZGSqyRzFEoUNGmOGxM6jw/rJoV80nV_OGVRxR7Jj2T9OT-9UzMNU8o6a-F-pDVS5osiIQkeZe-MZJMol7iEUN0_WZpSgDpuZRtrJO8qUpx_Y5qeqA0vwl77FyuhoF4elp32fYixYGDx8E_J0G4r9f_sTVEpCIg0oGBhXZXsfbGo_LwgKNH17YaHSOCJ1h0Bdk/kN3IUGgeYWjN1NpLEMJ4wZBGJYlIIV9QWfMwDWbIg1w', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recpX9F9ctmF2Y4tN', 'eis-girona', 'EIS Girona', 'Av. Sant Narcís, 32, baixos, 17005 Girona', '972 23 59 39', 'info@eisgirona.com', 'https://www.eisgirona.com/', 'Girona - Sant Narcís', 'Descobreix l''escola d''idiomes més cool de Girona! Cursos per a totes les edats i nivells. Aprèn, gaudeix i marca la diferència!
', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/sBnSCzbmfHVjRdvdXcArxw/7mPfCLx67L_cp9rM-ApOQaeA8dz9XWsG4PcfWsJ48oc6HFONZI7t8O33yE5dFD2S0N8EaQNbsJDpz1tqab5NcTZrcZrKlm8izss00xOriPmsJdhaiwQD-gzjbAf86qr89-oMvKm8MWb2QkEMmMhDnA/3R7XrNG6P1taAfMpTn1eM5cNq4u_-Evet0BAtG0KttI', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recpuHm6vYTtvr62n', 'afa-pla-girona', 'AFA Pla de Girona', 'Girona', '972418500', 'afapladegirona@gmail.com', 'afapladegirona.com', '', 'Associació de famílies de l''escola Pla de Girona. Organitza activitats extraescolars: esports', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recqvpFVi3AIgBlLn', 'ballem-escola-dansa-marc-bertran-girona', 'Ballem - Escola dansa Marc Bertran', 'Carrer Puigcogul, 59', '674818970', 'ballemfaraway@gmail.com', 'https://www.instagram.com/escoladansaballem/', 'Cassà de la Selva', 'Classes d''iniciació a la dansa, dansa clàssica, jazz, contemporani, salsa i bachata, danses urbanes, locking, zumba, pilates i barre. Oferim classes a partir dels 3 anys
', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/_7CJKRU9NEtjVieRNBrxCw/l8o8yu1yUj7iNScUm3xuiTjHvb3A1cfZRLVv_0D2IBhqmU01jOSVbccGusG2uK_iF6a-XvJKTAUtvb2zcuS3Bh8yaaOD4GKlk98Nx78pgnj_kufqTnIdrcW5XKnsRKe59oJK507oYWKdY-UeGXEH8cxCMroZvZBH_DiuANtCcNg/4JHRXSmq3F3u9wYHe8mzMVaYtpxzauX3B3OL1C-C_uM', TRUE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recro4p9CMkvvRHea', 'centre-de-proves-girona', 'Centre de proves', '', '', '', '', '', '', '', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recs9ZgVEqRpmjJwt', 'la-bullidora-girona', 'La Bullidora', 'Carrer de la Rutlla, 112-114', '692 125 228', 'labullidora@labullidora.com', 'https://labullidora.com/', 'Girona - Eixample', 'La Bullidora és un espai creatiu de la nostra ciutat, Girona on trobareu activitats educatives, creatives i terapèutiques encarades a incentivar la capacitat creadora de les persones.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/HyEHSohCezbcJupLgV0Dkw/s11y5zWT9_Po-qWQTLn0MfvWUwpDU-XHda37o3zTy-kI_o1l2gfOUPED3uRQvi49N2rkXVb5lEqLbejytdWgDQn0xuGgShgEfLJlY2ySd7hWfBlagqZH3WICIOaJRseN-vpOk30Afrg2QMNIEodI8UNoHvuUwFOQBKVYm7cSdgE/ndbSVUP-xxeMVvis3vFqOMRxlWwZ6xcG83dZK_1fKI0', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recsBRHdv4X6Q3V3T', 'la-moderna-girona', 'La Moderna', 'Plaça dels Jurats 1, Girona', '682 483 088', 'emmg@emmg.info', 'https://www.emmg.info/', 'Girona - Barri Vell', 'Facilitem l’accés a la pràctica musical a totes les edats, acompanyant-ne els interessos formatius i expressius.

Estem compromesos amb la qualitat educativa i entenem l’art com un àmbit de socialització i de gaudi al servei de les persones, col·lectius i agents culturals.

Liderem l’ensenyament de les músiques actuals a les comarques gironines, on hem esdevingut una institució clau per l’abast de les activitats socioeducatives que duem a terme.

Actualitzem permanentment la nostra oferta formativa i estem activament vinculats amb la vida cultural i social de la ciutat i de les comarques gironines.

', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/6S9dPlrEF6JVbx0lnxV98w/I9iEQDRXkjam52MIkEgvtwrwgdXuxzwstRJ8GY_cVpitFZKNF9bmC54Jw1tez4e8Ot3HkmmlgxpdHufcWw_lJcg4w1aMZ0826oXdhsQdkth5S6PdvWIJnBz3u1birNm_tA1C2pj3JfjUNMBeZDV50TC2CKPrkFBLMBr8js438AQ/EbWvAPHuKoX4ETDVkXqPHCU8Bp05IVr-pbgI6fjY2KM', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('rectjHA1UdfdJwFGp', 'nova-eruditio-girona', 'Nova Eruditio', 'Carrer Sant Roc, 2', '623 195 444', 'univers@novaeruditio.com', 'https://www.novaeruditio.com/', 'Girona - Montilivi-Palau', 'Empresa d’activitats extraescolars innovadores, creatives i divertides a Girona: LEGO Education ROBOTIX, matemàtiques, jocs de taula i mindfulness', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/Sny6-qBxFwTwnjKHtUPyLA/FMdqmgW_s7poeGAPhZGN70IvcaTEq_68GgAn2UfjH23NPjmV4AOxTgS17FPHVLry6JoV4og_Nc2FsvLEfntP1ufrG_KSk6oaNo79p8xWj78L8xEWaCJ1IT081alW16uQYcEHyWlvyo1-A1IUm3G9og/tOStt0KxIcTlRhMVICjI7IYQHXwHdd_yBMZI6DC6lYc', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recuVMFgq71oGAMBx', 'centre-civic-pla-palau-girona', 'Centre Cívic Pla de Palau', 'C. Saragossa, 27', '972 426 390', 'ccpalau@ajgirona.cat', 'www.girona.cat/ccivics', 'Girona - Montilivi-Palau', 'El Centre Cívic Pla de Palau comparteix edifici amb la Biblioteca Ernest Lluch i atén un sector molt ampli de la ciutat: Eixample, Palau, Montilivi, Avellaneda-Torres de Palau, Girona II, Torre Rafaela, plaça Josep Irla i Bosch, Mas Jardí, Puigvistós. La zona de més influència és Palau, Montilivi i Eixample.', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/eOn1aLj9xOWwZcc5CwIJ8A/7IyH6EqqIIhxo1khDk2hkz-Gps5uhGuDiq-pY2Y__3fscoH0U6D0S5zzMqxwKxs7rFkY2RYe1av7Y2cMaNjYFo5-fI7oTsr6flc5sFyqRM8FrHOpQkhUN9xWShtjAzD-ID5XqBjmoEgUvr2vSKkGR6CXGlVAnQd3AmY0bOkwYAM/m0sgNWHpliGjsU-REkuv4vL4me32Wk5wf2KRw5cpBg8', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;
INSERT INTO public.centres (id, slug, nom, adreca, telefon, email, web, barri, descripcio, imatge_url, interessat, vacances, ciutat)
VALUES ('recxIDKngKPeiAZRA', 'paco-morgado-girona', 'Escola d´art Paco Morgado', 'Carrer de Francesc Macià, 63, 17190 Salt, Girona', '606 68 08 04', 'escolapacomorgado@hotmail.es', 'https://escoladartpacomorgado.cat/', 'Salt', 'desenvolupa la tècnica específica d’aquest esport. Els infants aprendran a', 'https://v5.airtableusercontent.com/v3/u/55/55/1783540800000/pLJO5ijMaZGY8NejJ5Xk8Q/0oDIyN3q5cOJhrtMw6tQgPGukzYm7xBe9iVoL21YyAAtYp9dmoWlxke20BIILMXPTyUXf1MPOYnhC44rdsna6An-eSOBvUdPXgRp38rD2f64oFdfwCISgc8n0PO_CwdqZ6mXMP5mpefJjuX4ZgWVKMNFAUGQ9ZVQWDgt0eRCUBk/lmuyobp4J6mMMDMn_UUtNEeUpTJEy0u3LvH4gTJ87FY', FALSE, '', 'girona')
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug, nom = EXCLUDED.nom, adreca = EXCLUDED.adreca, telefon = EXCLUDED.telefon, email = EXCLUDED.email, web = EXCLUDED.web, barri = EXCLUDED.barri, descripcio = EXCLUDED.descripcio, imatge_url = EXCLUDED.imatge_url, interessat = EXCLUDED.interessat, vacances = EXCLUDED.vacances;

